### ISSUE TITLE
Technology Evaluation

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles-thesis#2]
_From @lukasmartinelli on November 20, 2015 10:43_
- [x] Tileserver @manuelroth 
- [x] Import @lukasmartinelli
- [x] Vector Tile Format vs Geopackage #9 @lukasmartinelli 
- [x] Datenbank (wieso PostGIS?) auf Open Streetmap Wiki (dort steht wieso PostgreSQL) @manuelroth 
- [ ] Datenquellen: wieso Natural Earth?, wieso Grenzen separat? -> kommt aber in Implementation  @lukasmartinelli

Wir in BA Arbeit gemacht:
- AWS SQS? wieso nicht RabbitMQ
- AWS / Google Cloud (sollen wir überhaupt reinnehmen?
- AWS Logging?
- Wieso pgbouncer vs andere Balancer

Wahrscheinlich macht es Sinn die Evaluation erst zu bringen, wenn der ganze Workflow klar ist.
**Klärung:** In technischer Bericht ist Workflow schon klar.

_Copied from original issue: manuelroth/osm2vectortiles-thesis#33_

**Comment by lukasmartinelli** [comment]
Evaluation soll in das Projektdokumentation Kapitel gehen.

**Comment by lukasmartinelli** [comment]
- [x] Es fehlen noch so Entscheidungsboxen @lukasmartinelli
- [ ] Erzählen von Erfahrungen der Kartotherian Menschen
