### ISSUE TITLE
Anforderungsspezifikation

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles-thesis#20]
**Anforderungsspezifikation**

Was ist mit Anforderung an die Arbeit?
- Mapbox kompatibel? **wieso**? <- vielleicht schon oberer Teil
- Restriction vom Format: kleiner als 500KB und Featureanzahl begrenzt
- Performance - schaffen wir es die Schweiz / Welt zu rendern?
- Visuell - sieht gleich aus
- Einfach zu benutzen (Kitematic, USB Idee)
- Einfach zu deployen -> Docker

Use Cases:
- Clientside Rendering mit Mapbox GL
- Serverside Rendering mit Raster Tiles
- Du kannst selber PostgreSQL haben und selber Tiles exportieren

**Comment by lukasmartinelli** [comment]
- [x] Herr Keller fragen ob Use Case Diagramm nötig da User Stories in Prosa beschrieben
- [x] NFR nochmals überlegen was wir noch hinzutun können (max. Anzahl Features pro Tile)
- [x] Akzeptanzkriterien hinzufügen
