### ISSUE TITLE
Stand der Technik

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles-thesis#4]
_From @lukasmartinelli on November 20, 2015 10:19_
- Anhand http://www.macwright.org/presentations/jsgeo/notes/ vorgehen um alte Welt / Zwischenwelt und neue Welt zu erklären
- Mapbox in GIS Welt?
- Defizite aufdecken (Vendor Lockin, Nachladen beim reinzoomen, nur ein Style bei Mapbox, keine Offline Apps weil Daten nicht lokal verfügbar)
- Unsere Lösung löst welche Defizite?

_Copied from original issue: manuelroth/osm2vectortiles-thesis#31_

**Comment by manuelroth** [comment]
_From @lukasmartinelli on November 20, 2015 13:2_

> Zweck und Inhalt dieses Kapitels.
> Was machen andere / welche ähnlichen Arbeiten gibt es zum Thema? Was kann von anderen verwendet 
> werden?
> Diese Einleitung soll für den Ingenieur irgendeiner Fachrichtung verständlich sein. Sie stellt die Aufgabe 
> in einen grösseren Zusammenhang und liefert eine genaue Beschreibung der Problemstellung. Allfällige 
> Vorarbeiten oder ähnlich gelagerte Arbeiten werden diskutiert. 
> Theoretische Grundlagen sind nur so weit auszuarbeiten, als dies für die Lösung der Aufgabe nötig ist 
> (keine Lehrbücher schreiben). Die Erkenntnisse aus den theoretischen Untersuchungen sind wenn immer möglich direkt mit der Problemlösung zu verknüpfen.

**Comment by lukasmartinelli** [comment]
Wieso sollte man Mapbox statt Google Maps nehmen.

Mit Google kann man die Karten nur begrenzt stylen - mit Mapbox ist alles möglich.
