### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/osm2vectortiles-thesis#8]
**Implementation**

Architektur ist in Stack Beschreibung (Analyse) und hier geht es um Details.
- Source Projekt
  - [x] Wie funktioniert tm2source Format @manuelroth 
  - [x] Was wird wo ausgeblendet #12 @manuelroth
  - [x] Tileserver Implementation (tessera) @lukasmartinelli
  - Tools
    - [x] Gatling @manuelroth 
    - [x] Verify und andere Python Skripts @lukasmartinelli  
  - [x] Postgres (Plugins und welches Tuning damit schnell) @lukasmartinelli
- Reverse Engineering @manuelroth
  - [x] Vector Tile Beschreibung
  - [x] Vector Tile Compare @manuelroth 
  - [x] Visual Compare @lukasmartinelli

Was nehemen wir in SA und in BA? Lassen wir Cloudgeschichte weg
- Testing @lukasmartinelli 
  - wie sind wir vorgegangen?
  - unser Workflow für QA?
  - Continuous Integration

**Comment by lukasmartinelli** [comment]
Müssen wir später nochmals anschauen.
